### ISSUE TITLE
'Other' is being added as a subcategory and breaks uploading

### ISSUE THREAD

**Issue by ineeee** [lesmo/BlackSam#8]
_(I have no idea how this Issues thing works)_

At line 57 of [app/views/torrent/upload.jade](https://github.com/lesmo/BlackSam/blob/master/app/views/torrent/upload.jade#L57), the script is appending _Other_ to all of the categories, which is invalid because it's not defined in [config/categories.coffee](https://github.com/lesmo/BlackSam/blob/master/config/categories.coffee)
If _Other_ is chosen, uploading is impossible.

![image](https://cloud.githubusercontent.com/assets/10874672/6096304/122ac090-af69-11e4-9c59-a34620c026a8.png)

**Comment by lesmo** [comment]
_(It works exactly as you've just used it)_

[Line 57 of `app/views/torrent/upload.jade`](https://github.com/lesmo/BlackSam/blob/master/app/views/torrent/upload.jade#L57) generates that list, and it contains **Others** as an _alias_ for just the category name.

Problem is caused, probably, by the processing in [`app/controllers/torrent.coffee` (line 132)](https://github.com/lesmo/BlackSam/blob/master/app/controllers/torrent.coffee#L132). Probably the same issue that's been haunting the import process, timeouts...
